dist: trusty

language: java

addons:
  sonarcloud:
    organization: beatngu13-github
    token:
      secure: "${SC_TOKEN}"

cache:
  directories:
    - "${HOME}/.m2/"
    - "${HOME}/.sonar/cache/"

jdk: oraclejdk8

install: true

before_script: ./install-deps.sh

script: mvn clean verify sonar:sonar -Pcoverage

before_deploy: mvn package -DskipTests

deploy:
  provider: releases
  api_key: "${GH_TOKEN}"
  file_glob: true
  file: "./target/pdfzoomwizard-*.jar"
  skip_cleanup: true
  draft: true
  on:
    tags: true
