language: java

notifications:
  email: false
  
install: ./install-deps.sh
  
before_deploy: mvn package -DskipTests

deploy:
  provider: releases
  api_key: "${GH_TOKEN}"
  file_glob: true
  file: "./target/pdfzoomwizard-*.jar"
  skip_cleanup: true
  draft: true
  on:
    tags: true
