language: java
sudo: false

addons:
  sonarcloud:
    organization: beatngu13-github
    token:
      secure: "${SC_TOKEN}"

notifications:
  email: false

cache:
  directories:
    - "${HOME}/.m2/"
    - "${HOME}/.sonar/cache/"

install: true

before_script: ./install-deps.sh

script: mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent verify sonar:sonar

before_deploy: mvn package -DskipTests

deploy:
  provider: releases
  api_key: "${GH_TOKEN}"
  file_glob: true
  file: "./target/pdfzoomwizard-*.jar"
  skip_cleanup: true
  draft: true
  on:
    tags: true
