name: Run Git Flow goal

on:
  workflow_dispatch:
    inputs:
      gitFlowGoal:
        description: 'Goal (release-start, release-finish, hotfix-start or hotfix-finish)'
        required: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Set up JDK 8 with JavaFX
        uses: actions/setup-java@v1
        with:
          java-version: 8
          java-package: jdk+fx

      - name: Cache Maven
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository/
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install dependencies
        run: |
          ./install-deps.sh

      - name: Run Git Flow goal with Maven
        run: >
          mvn --batch-mode gitflow:${{ github.event.inputs.gitFlowGoal }}
